# Generated by Django 3.1.3 on 2021-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twmblog', '0005_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
